BCS/BCS/Controllers/ReportsBillingStatementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BCS.Models;
using Microsoft.AspNet.Identity;
using System.Configuration;
using System.Net;
using System.Collections.Specialized;

namespace BCS.Controllers
{

    public class ReportsBillingStatementController : Controller
    {

        //LOGS
        systemlogger SL = new systemlogger();
        //GET IP ADDRESS
        string ipaddress = Dns.GetHostAddresses(Dns.GetHostName())[1].ToString();

        // GET: ReportBillingStatement
        ApplicationDbContext context = new ApplicationDbContext();

        private BCS_Context db = new BCS_Context();

        public ActionResult ViewBillingStatement()
        {
            SearchReportsBillingStatementModels srchBS = new SearchReportsBillingStatementModels();

            srchBS.ZoneGroupList = db.ZoneGroup.SqlQuery("SELECT * FROM ZoneGroups EXCEPT SELECT * FROM ZoneGroups WHERE ZoneGroupName = 'Super User'").ToList();
            //srchBS.ZoneList = db.Zone.SqlQuery("Select * from Zones").ToList();
            var userid = User.Identity.GetUserId();
            string ZoneGroup = context.Users.SingleOrDefault(m => m.Id == userid).ZoneGroup;
      
            srchBS.BillingPeriodList = db.BillingPeriod.Where(m => m.groupCode == ZoneGroup).ToList();
            srchBS.EnterpriseTypeList = db.Database.SqlQuery<EnterpriseTypes>("SELECT DISTINCT EnterpriseType FROM Companies ORDER BY EnterpriseType ASC").ToList();
            srchBS.Companylist = db.Company.SqlQuery("Select * from Companies").ToList();
            srchBS.ZoneList = db.Zone.SqlQuery("Select * from Zones").ToList();
            return View("ViewBillingStatement", srchBS);
        }


        
        public JsonResult GetDevelopers()
        {
            var enterpriseList = db.Database.SqlQuery<EnterpriseTypes>("SELECT DISTINCT EnterpriseType FROM Companies ORDER BY EnterpriseType ASC").ToList();
            return Json(enterpriseList);
        }


        public JsonResult getcompany(string comp, string type)
        {
            List<BillingPaymentJsonReturnData> billingPaymentJsonReturnData = new List<BillingPaymentJsonReturnData>();
            SearchMainOrderOfPaymentViewModel searchop = new SearchMainOrderOfPaymentViewModel();

            if (type == "AdminFee")
            {
                if (comp.Length >= 3)
                {
                    var companies = db.Database.SqlQuery<DeveloperDetails>("SELECT DISTINCT Dev_Comp_Code, Developer, Zone_Code, Ecozone from AdminFees left join Zones on AdminFees.Zone_Code = Zones.ZoneCode where AdminFees.Developer like '%" + comp + "%'").ToList();

                    return Json(companies);
                }
            }

            else
            {
                if (comp.Length >= 3)
                {
                    var newcomp = comp.Replace("'", "''");
                    var complist = db.Company.SqlQuery("SELECT * FROM COMPANIES WHERE CompanyName like '" + newcomp + "%'").Take(15).ToList();
                     
                    foreach (var items in complist)
                    {
                        searchop.CompanyID.Add(db.Company.FirstOrDefault(x => x.CompanyID == items.CompanyID).CompanyID.ToString());
                        searchop.CompanyName.Add(db.Company.FirstOrDefault(x => x.CompanyID == items.CompanyID).CompanyName);
                        searchop.ZoneName.Add(db.Zone.FirstOrDefault(x => x.ZoneCode == items.ZoneCode).ZoneName);
                    }

                    for (int i = 0; i < searchop.CompanyName.Count; i++)
                    {
                        BillingPaymentJsonReturnData billingPaymentJsonReturnDataNew = new BillingPaymentJsonReturnData();
                        billingPaymentJsonReturnDataNew.CompanyID = Convert.ToInt32(searchop.CompanyID[i]);
                        billingPaymentJsonReturnDataNew.CompanyName = searchop.CompanyName[i].ToString();
                        billingPaymentJsonReturnDataNew.ZoneName = searchop.ZoneName[i].ToString();
                        billingPaymentJsonReturnData.Add(billingPaymentJsonReturnDataNew);
                    }
                    return Json(billingPaymentJsonReturnData);
                }  
            }

            return Json(null);
        }

        [HttpPost]
        public JsonResult returnCompany(string zonename, string zonegroupcode, string enttype, string comp)
        {
            SearchCompany companysearch = new SearchCompany();


            var userid = User.Identity.GetUserId();
            string ZoneGroupx = context.Users.SingleOrDefault(m => m.Id == userid).ZoneGroup;

            if (comp.Length >= 3)
            {
                if (zonegroupcode == null)
                {

                    if (enttype == "")
                    {
                        if (zonename == "All")
                        {
                            var selcom = from t1 in db.Company
                                         join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                         join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                         where t3.ZoneGroupCode == ZoneGroupx
                                         orderby t1.CompanyName
                                         select t1;
                            companysearch.CompanyList = selcom.ToList();
                        }
                        else
                        {
                            var selcom = from t1 in db.Company
                                         join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                         join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                         where t3.ZoneGroupCode == ZoneGroupx && t2.ZoneCode == zonename && t1.CompanyName.StartsWith(comp)
                                         orderby t1.CompanyName
                                         select t1;
                            companysearch.CompanyList = selcom.ToList();
                        }
                    }
                    else if (enttype == "All")
                    {
                        if (zonename == "All")
                        {
                            var selcom = from t1 in db.Company
                                         join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                         join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                         where t3.ZoneGroupCode == ZoneGroupx && t1.CompanyName.StartsWith(comp)
                                         orderby t1.CompanyName
                                         select t1;
                            companysearch.CompanyList = selcom.ToList();
                        }
                        else
                        {
                            var selcom = from t1 in db.Company
                                         join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                         join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                         where t3.ZoneGroupCode == ZoneGroupx && t2.ZoneCode == zonename && t1.CompanyName.StartsWith(comp)
                                         orderby t1.CompanyName
                                         select t1;
                            companysearch.CompanyList = selcom.ToList();
                        }
                    }
                    else
                    {
                        var selcom = from t1 in db.Company
                                     join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                     join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                     where t3.ZoneGroupCode == ZoneGroupx && t2.ZoneCode == zonename && t1.EnterpriseType == enttype && t1.CompanyName.StartsWith(comp)
                                     orderby t1.CompanyName
                                     select t1;
                        companysearch.CompanyList = selcom.ToList();

                    }

                }
                else
                {
                    if (enttype == "")
                    {
                        if (zonename == "All")
                        {
                            var selcom = from t1 in db.Company
                                         join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                         join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                         where t3.ZoneGroupCode == zonegroupcode && t1.CompanyName.StartsWith(comp)
                                         orderby t1.CompanyName
                                         select t1;
                            companysearch.CompanyList = selcom.ToList();
                        }
                        else
                        {
                            var selcom = from t1 in db.Company
                                         join t2 in db.Zone on t1.ZoneCode equals t2.ZoneCode
                                         join t3 in db.ZoneGroup on t2.ZoneGroup equals t3.ZoneGroupId.ToString()
                                         where t3.ZoneGroupCode == zonegroupcode && t2.ZoneCode == zonename && t1.CompanyName.StartsWith(comp)
                                         orderby t1.CompanyName
                                         select t1;
                            companysearch.CompanyList = selcom.ToList();
                        }
                    }
                    else if (enttype == "All")
                    {
                        if (zonename == "All")
                        {

BCS/BCS/Controllers/ReportsEmailController.cs
using BCS.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;



namespace BCS.Controllers
{
    public class ReportsEmailController : Controller
    {

        //LOGS
        systemlogger SL = new systemlogger();
        //GET IP ADDRESS
        string ipaddress = Dns.GetHostAddresses(Dns.GetHostName())[1].ToString();

        private BCS_Context db = new BCS_Context();
        // GET: ReportsEmail
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ViewReportsEmail()
        {

            SearchCompanyForEmail srch = new SearchCompanyForEmail();

            srch.companylist = db.Company.Where(c => c.SendEmail == "Yes").ToList();

            return View(srch);

        }

        [HttpPost]
        public ActionResult ViewReportsEmail(string atats, string foremail, string forsubject, string forbody, string[] langOpt3, HttpPostedFileBase fileUploader)
        {
            var emailvar = new List<string>();
            SearchCompanyForEmail srch = new SearchCompanyForEmail();

            srch.companylist = db.Company.Where(c => c.SendEmail == "Yes").ToList();

            //string path = "C:/Users/dev2/Documents/IAN/PROJECT FILES/Email/09072016/PBCS 9-6-16 5PM(CONSO)/BCS/BCS/PDF/GeneralBillingStatements.pdf";
            string path2 = HostingEnvironment.ApplicationPhysicalPath + atats;

            bool boleen = System.IO.File.Exists(path2);

            int x = langOpt3.Count() - 1;

            for (int i = 0; i <= x; i++)
            {

                var y = langOpt3[i];

                var ev = db.Company.SingleOrDefault(co => co.CompanyName == y).PrimaryEmailAddress;
                var ev2 = db.Company.SingleOrDefault(co => co.CompanyName == y).SecondaryEmailAddress;

                emailvar.Add(ev.ToString());
                emailvar.Add(ev2.ToString());
                if (ModelState.IsValid)
                {




                    var message = new MailMessage();
                    message.To.Add(new MailAddress(ev)); //replace with valid value
                    message.Subject = forsubject;
                    message.Body = forbody;
                    message.IsBodyHtml = true;
                    message.Attachments.Add(new Attachment(path2));





                    var message2 = new MailMessage();
                    message2.To.Add(new MailAddress(ev2)); //replace with valid value
                    message2.Subject = forsubject;
                    message2.Body = forbody;
                    message2.IsBodyHtml = true;
                    message2.Attachments.Add(new Attachment(path2));




                    using (var smtp = new SmtpClient())
                    {
                        try
                        {
                            smtp.Send(message);
                            smtp.Send(message2);
                            ViewBag.Message = "Sent";
                            SL.LogInfo(User.Identity.Name, Request.RawUrl, "Reports Email - Email Sent  - from Terminal: " + ipaddress);

                        }
                        catch
                        {
                            ViewBag.Message = "Not Sent";
                            SL.LogInfo(User.Identity.Name, Request.RawUrl, "Reports Email - Email Not Sent  - from Terminal: " + ipaddress);

                        }




                    }


                }
            }


            return View("ViewReportsEmail", srch);
        }
    }
}

BCS/BCS/Views/ReportsBillingStatement/ReportsEmail/ViewReportsEmail.cshtml
@model BCS.Models.SearchCompanyForEmail
@{
    ViewBag.Title = "ViewReportsEmail";
}

<!-- Include the plugin's CSS and JS: -->
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script>
    $(document).ready(function () {
        if ('@ViewBag.Message' == 'Sent') {
            alert('Mail has been sent successfully');
        } else if ('@ViewBag.Message' == 'Not Sent') {
            alert('Mail Not Sent! Contact your Administrator');
        }
    });
</script>
<div class="modal-dialog">
    <div class="modal-content ">
        <div class="modal-header">
            <h4 class="fontBld"><span class="glyphicon glyphicon-envelope"></span>&nbsp; Email</h4>
        </div>
        <div class="modal-body bgColor-lv">


            @using (@Html.BeginForm("ViewReportsEmail", "ReportsEmail", FormMethod.Post, new { @id = "form1", @enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary()

                <table>
                    <tr>
                        <td>Select Company </td>
                        <td>

                            <select name="langOpt3[]" id="langOpt3" class="form-control" multiple="multiple" required>
                                @*<select class="form-control" id="sel1">*@
                                @foreach (var item in Model.companylist)
                                {
                                    <option value="@item.CompanyName">@item.CompanyName</option>
                                }
                            </select>

                        </td>
                    </tr>
                    <tr>
                        <td>
                            Subject:
                        </td>
                        <td>
                            <input name="forsubject" type="text" class="form-control" placeholder="Subject" required />
                        </td>
                    </tr>

                    <tr>
                        <td>
                            Select list:
                        </td>
                        <td>

                            <div class="form-group">
                                <select name="atats" class="form-control" id="sel1" required>
                                    <option value="PDF\GeneralBillingStatements\GeneralBillingStatements.pdf">General Billing Statements</option>

                                </select>
                            </div>
                            @*<input type="file" name="fileUploader" class="btn btn-default" />*@
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Remarks:
                        </td>
                        <td>
                            <textarea class="form-control" name="forbody" required></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td></td>

                        <td>
                            <input type="submit" value="Send" class="btn btn-primary w300px" />
                        </td>
                    </tr>
                </table>
            }

        </div>
        <div class="modal-footer">



        </div>
    </div>

</div>

<script src="~/Scripts/jquery.min.js"></script>
@*<script src="~/Scripts/jquery.multiselect.js"></script>*@
<script>
    @*<!-- Initialize the plugin: -->*@

    $(document).ready(function() {
        $('#langOpt3').multiselect({
            enableFiltering: true,
            includeSelectAllOption: true,
            
            maxHeight: 180,
            buttonWidth: '300px',
           


        });
    });




</script>