BCS/BCS/Controllers/MaintenanceVATController.cs
using BCS.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BCS.Controllers
{
    public class MaintenanceVATController : Controller
    {
        // GET: DataEntryVAT
        public ActionResult ViewVAT()
        {
            return View();
        }

        // Generate Report
        public ActionResult VATReport(string reportType)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var userid = User.Identity.GetUserId();
            string zoneGroupCode = context.Users.SingleOrDefault(m => m.Id == userid).ZoneGroup;

            return Redirect("/Reports/Report.aspx?reportType=" + reportType + "&zoneGroupCode=" + zoneGroupCode);
        }
    }
}

BCS/BCS/Views/MaintenanceVAT/ViewVAT.cshtml
@{
    ViewBag.Title = "ViewVAT";
}
<div ID="searchField" class="container">
    <CENTER><H2 CLASS="fcWhite">VAT</H2></CENTER>
    <div class="container bgColor-White">
        <p></p>
        <div CLASS="floatLeft w100per pad5">
            <div CLASS="br2">
                <table CLASS="zeroSpace w100per txtSize12px">
                    <tr class="br1-bot">
                        <td class="w20per pad5 bgColor-lb">
                            <B>COMPANY</B>
                        </td>
                        <td class="w80per pad5">
                            Pilipinas Express Logistics
                        </td>
                    </tr>
                    <tr>
                        <td class="w20per pad5 bgColor-lb">
                            <B>ADDRESS</B>
                        </td>
                        <td class="w80per pad5">
                            Mactan, Philippines
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <!-- Trigger the modal Search Enterprise with a button -->
        <center class="pad10"><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalSearchEnterprise">Search Enterprise</button></center>
        <center class="pad10">@Html.ActionLink("View Report", "VATReport", "MaintenanceVAT", new { reportType = "VATAlphaList" }, new { @class = "btn btn-primary btn-sm", Type = "button", target = "_blank" })</center>    
    </div>
    <div class="container bgColor-White">
        <p></p>
        <DIV>
            <DIV CLASS="floatLeft w100per pad5">
                <DIV CLASS="br2 pad5">
                    <CENTER CLASS="br1-bot bgColor-lb"><B>Taxable Items</B></CENTER>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-3 txtCenter fontBld">Transaction No</div>
                            <div class="col-sm-2 txtCenter fontBld">Type</div>
                            <div class="col-sm-3 txtCenter fontBld">Percentage</div>
                            <div class="col-sm-2 txtCenter fontBld">Start date</div>
                            <div class="col-sm-2 txtCenter fontBld">Cancelled</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3 txtCenter fontBld h25px cell br1Grey"></div>
                            <div class="col-sm-2 txtCenter fontBld h25px cell br1Grey"></div>
                            <div class="col-sm-3 txtCenter fontBld h25px cell br1Grey"></div>
                            <div class="col-sm-2 txtCenter fontBld h25px cell br1Grey pad0"><input type="button" class="w100per h25px br0" id="inputWarning" value="HISTORY" data-toggle="modal" data-target="#modalAdvancesHistory"></div>
                            <div class="col-sm-2 txtCenter fontBld h25px cell br1Grey"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3 txtCenter fontBld h25px cell br1Grey"></div>
                            <div class="col-sm-2 txtCenter fontBld h25px cell br1Grey"></div>
                            <div class="col-sm-3 txtCenter fontBld h25px cell br1Grey"></div>
                            <div class="col-sm-2 txtCenter fontBld h25px cell br1Grey pad0"><input type="button" class="w100per h25px br0" id="inputWarning" value="HISTORY" data-toggle="modal" data-target="#modalAdvancesHistory"></div>
                            <div class="col-sm-2 txtCenter fontBld h25px cell br1Grey"></div>
                        </div>
                    </div>
                    <table CLASS="w100per">
                        <tr>
                            <td CLASS="pad20"></td>
                            <td CLASS="w10per pad20"><input type="button" VALUE="ADD" class="btnH-lg w100per" id="inputWarning" data-toggle="modal" data-target="#modalAddVAT"></td>
                            <td CLASS="w10per pad20"><input type="button" VALUE="EDIT" class="btnH-lg w100per" id="inputWarning"></td>
                            <td CLASS="w10per pad20"><input type="button" VALUE="REMOVE" class="btnH-lg w100per" id="inputWarning"></td>
                            <TD CLASS="w20per pad20"><input type="button" VALUE="PREVIEW ALPHA LIST" class="btnH-lg w100per" id="inputWarning"></TD>
                        </tr>

                    </table>
                </DIV>
 
            </DIV>

        </DIV>
    </div>
</div>

<!-- Modal Search Enterprise-->
<div class="modal fade" id="modalSearchEnterprise" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" data-target="#modalSearchEnterprise" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><span class="glyphicon glyphicon-folder-open"></span> Enterprise Information</h4>
            </div>
            <div class="modal-body bgColor-lv">
                <!--<div class="pad10 bgColor-White h100px br1Grey ovrFlw-YAuto">
                    <span class="glyphicon glyphicon-dashboard"></span> <b>TIPS:</b>
                    <ol>
                        <li>Enter search sequence in the textfield then click <b>Search</b> button. <br /></li>
                        <li>Select an enterprise and press <b>ok</b> button. </li>
                        <li>Click <b>Cancel</b> or <b>X</b> button or outside the pop-up screen to exite pop-up screen</li>
                    </ol>
                </div>
                <br />-->
                <div class="pad5 btn-primary fontBld">
                    <div class="container">
                        <div class="col-sm-3 pad0">Company Name</div>
                        <div class="col-sm-7 br1Grey bgColor-White h25px"> </div>
                        <div class="col-sm-2 pad0"> <button type="button" class="h25px w100per">Search</button></div>
                    </div>
                </div>
                <div class="pad10 bgColor-White h100px br1Grey ovrFlw-Y"></div>
            </div>
            <div class="modal-footer">
                <div class="col-sm-4"></div>
                <div class="col-sm-4"><button type="button" class="btn btn-primary w100px" data-dismiss="modal">OK</button></div>
                <div class="col-sm-4"><button type="button" class="btn btn-primary w100px" data-dismiss="modal">Cancel</button></div>
            </div>
        </div>

    </div>
</div>
<!-- End Modal Search Enterprise-->

<!-- Modal Add VAT-->
<div class="modal fade" id="modalAddVAT" role="dialog">
    <div class="modal-dialog">

        <!-- Modal Add VAT Content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-toggle="modal" data-target="#modalAddVAT">&times;</button>
                <h4 class="modal-title">Add VAT</h4>
            </div>
            <div class="modal-body bgColor-lv">
                <h4><span class="glyphicon glyphicon-plus icon clr"></span> Taxable Item</h4>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-sm-9">
                        <button type="button" class="btn btn-primary w100px" data-toggle="modal" data-target="#modalAddVAT">Yes</button>
                    </div>
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-primary w100px" data-toggle="modal" data-target="#modalAddVAT">No</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- End Modal Add VAT-->